"""core business tables: employee_salaries, purchases, expenses, daily_revenue, cash_ledger, cheques

Revision ID: 0008
Revises: 0007
Create Date: plan section 8.9 / 12.1-12.6

The six core supermarket workflows, stored natively as real typed tables. Each
is also registered as a row in `pages` with `is_system = true` and
`storage_table` set, so the generic page-engine surface (record endpoints, AI
discovery tools, dynamic forms, page_access grants, protected columns, audit)
works over them unchanged. A system page has NO rows in `records`.

Deliberately simple: no quantity/unit-cost breakdowns, no payment status, no
approval workflows, no per-expense-type tables. See ADR 0006.
"""

from __future__ import annotations

from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None

BUSINESS_TABLES = [
    "employee_salaries",
    "purchases",
    "expenses",
    "daily_revenue",
    "cash_ledger",
    "cheques",
]

# The platform columns every business table carries, mirroring `records` so the
# service layer can treat both storage backends uniformly.
SHARED_COLUMNS = """
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    store_id        UUID REFERENCES stores(id),
    occurred_at     TIMESTAMPTZ NOT NULL,
    business_date   DATE NOT NULL,
    status          record_status NOT NULL DEFAULT 'ACTIVE',
    needs_review    BOOLEAN NOT NULL DEFAULT FALSE,
    created_by      UUID NOT NULL REFERENCES users(id),
    updated_by      UUID REFERENCES users(id),
    source          TEXT NOT NULL DEFAULT 'APP',
    client_uuid     UUID,
    import_batch_id UUID,
    version         INTEGER NOT NULL DEFAULT 1,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_reason  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
"""


def upgrade() -> None:
    # --- pages becomes able to describe a natively-stored page -------------
    op.execute("ALTER TABLE pages ADD COLUMN is_system BOOLEAN NOT NULL DEFAULT FALSE;")
    op.execute("ALTER TABLE pages ADD COLUMN storage_table TEXT;")  # NULL = stored in `records`

    op.execute("CREATE TYPE cheque_status AS ENUM ('PENDING','PAID');")

    # --- employee_salaries (plan section 12.1) -----------------------------
    # One record = one salary payment. Deliberately minimal: no basic/OT/bonus/
    # allowances/deductions/net-salary breakdown, no payment status or method.
    op.execute(
        f"""
        CREATE TABLE employee_salaries (
            {SHARED_COLUMNS}
            payment_date  DATE NOT NULL,
            employee_name TEXT NOT NULL,
            paid_amount   NUMERIC(14,2) NOT NULL CHECK (paid_amount >= 0),
            reference     TEXT
        );
        """
    )

    # --- purchases (plan section 12.2) -------------------------------------
    # No quantity, unit cost, item lines, status or settlement workflow.
    op.execute(
        f"""
        CREATE TABLE purchases (
            {SHARED_COLUMNS}
            purchase_date DATE NOT NULL,
            entry_time    TIMESTAMPTZ NOT NULL DEFAULT now(),
            purchase_name TEXT NOT NULL,
            total_amount  NUMERIC(14,2) NOT NULL CHECK (total_amount >= 0)
        );
        """
    )

    # --- expenses (plan section 12.3) --------------------------------------
    # expense_name is free text ("Electricity", "Rent", "Water", ...): expense
    # types are values, never separate tables and never a fixed option list.
    op.execute(
        f"""
        CREATE TABLE expenses (
            {SHARED_COLUMNS}
            expense_date DATE NOT NULL,
            entry_time   TIMESTAMPTZ NOT NULL DEFAULT now(),
            expense_name TEXT NOT NULL,
            amount       NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
            description  TEXT
        );
        """
    )

    # --- daily_revenue (plan section 12.4) ---------------------------------
    # total_revenue is generated by the database in NUMERIC (Decimal), so it can
    # never disagree with its inputs.
    op.execute(
        f"""
        CREATE TABLE daily_revenue (
            {SHARED_COLUMNS}
            entry_date    DATE NOT NULL,
            cash_sales    NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cash_sales >= 0),
            card_sales    NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (card_sales >= 0),
            total_revenue NUMERIC(14,2) GENERATED ALWAYS AS (cash_sales + card_sales) STORED
        );
        """
    )

    # --- cash_ledger (plan section 12.5) -----------------------------------
    op.execute(
        f"""
        CREATE TABLE cash_ledger (
            {SHARED_COLUMNS}
            entry_date        DATE NOT NULL,
            cash_amount       NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (cash_amount >= 0),
            card_sales_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (card_sales_amount >= 0),
            total_amount      NUMERIC(14,2)
                              GENERATED ALWAYS AS (cash_amount + card_sales_amount) STORED
        );
        """
    )

    # --- cheques (plan section 12.6) ---------------------------------------
    # `status` is the protected column: managers create cheques (always PENDING)
    # but only an OWNER may change the value. No approval workflow.
    op.execute(
        f"""
        CREATE TABLE cheques (
            {SHARED_COLUMNS}
            cheque_number TEXT NOT NULL,
            payee_name    TEXT,
            amount        NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
            cheque_date   DATE,
            -- named cheque_status, not status: `status` is already the platform
            -- record lifecycle (ACTIVE/REVERSED/VOID) on every business table.
            -- Displayed to the Owner as "Status".
            cheque_status cheque_status NOT NULL DEFAULT 'PENDING',
            reference     TEXT
        );
        """
    )

    # --- shared indexes + offline idempotency ------------------------------
    for table in BUSINESS_TABLES:
        op.execute(
            f"""
            CREATE INDEX ix_{table}_company_time ON {table} (company_id, business_date DESC)
                   WHERE is_deleted = FALSE;
            """
        )
        op.execute(f"CREATE INDEX ix_{table}_store ON {table} (store_id, business_date DESC);")
        op.execute(
            f"""
            CREATE UNIQUE INDEX ux_{table}_client_uuid ON {table} (company_id, client_uuid)
                   WHERE client_uuid IS NOT NULL;
            """
        )

    # --- per-table indexes on the business columns queried most ------------
    op.execute(
        "CREATE INDEX ix_employee_salaries_date ON employee_salaries (payment_date) WHERE is_deleted = FALSE;"
    )
    op.execute(
        "CREATE INDEX ix_employee_salaries_employee ON employee_salaries (employee_name) WHERE is_deleted = FALSE;"
    )
    op.execute(
        "CREATE INDEX ix_purchases_date ON purchases (purchase_date) WHERE is_deleted = FALSE;"
    )
    op.execute(
        "CREATE INDEX ix_purchases_amount ON purchases (total_amount) WHERE is_deleted = FALSE;"
    )
    op.execute("CREATE INDEX ix_expenses_date ON expenses (expense_date) WHERE is_deleted = FALSE;")
    op.execute("CREATE INDEX ix_expenses_amount ON expenses (amount) WHERE is_deleted = FALSE;")
    op.execute("CREATE INDEX ix_expenses_name ON expenses (expense_name) WHERE is_deleted = FALSE;")
    op.execute(
        "CREATE INDEX ix_daily_revenue_date ON daily_revenue (entry_date) WHERE is_deleted = FALSE;"
    )
    op.execute(
        "CREATE INDEX ix_cash_ledger_date ON cash_ledger (entry_date) WHERE is_deleted = FALSE;"
    )
    op.execute("CREATE INDEX ix_cheques_date ON cheques (cheque_date) WHERE is_deleted = FALSE;")
    op.execute("CREATE INDEX ix_cheques_amount ON cheques (amount) WHERE is_deleted = FALSE;")
    op.execute(
        "CREATE INDEX ix_cheques_status ON cheques (cheque_status) WHERE is_deleted = FALSE;"
    )

    # --- daily reconciliation (plan section 12.5) --------------------------
    # Daily Revenue total vs Cash Ledger total for the same business date.
    # FULL OUTER JOIN so a date present in only one of the two still appears.
    # security_invoker makes the view respect the caller's RLS on both tables.
    op.execute(
        """
        CREATE VIEW daily_reconciliation WITH (security_invoker = true) AS
        SELECT
            COALESCE(r.company_id, l.company_id)       AS company_id,
            COALESCE(r.business_date, l.business_date)  AS business_date,
            COALESCE(r.revenue_total, 0)                AS revenue_total,
            COALESCE(l.ledger_total, 0)                 AS ledger_total,
            COALESCE(r.revenue_total, 0) - COALESCE(l.ledger_total, 0) AS difference
        FROM (
            SELECT company_id, business_date, SUM(total_revenue) AS revenue_total
            FROM daily_revenue
            WHERE is_deleted = FALSE AND status = 'ACTIVE'
            GROUP BY company_id, business_date
        ) r
        FULL OUTER JOIN (
            SELECT company_id, business_date, SUM(total_amount) AS ledger_total
            FROM cash_ledger
            WHERE is_deleted = FALSE AND status = 'ACTIVE'
            GROUP BY company_id, business_date
        ) l ON l.company_id = r.company_id AND l.business_date = r.business_date;
        """
    )

    # --- RLS, matching the pattern in 0006_rls_policies ---------------------
    for table in BUSINESS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (company_id = current_setting('app.company_id', true)::uuid);
            """
        )
        op.execute(
            f"""
            CREATE POLICY store_scope ON {table}
              USING (
                current_setting('app.role', true) = 'OWNER'
                OR store_id IS NULL
                OR store_id = ANY (string_to_array(current_setting('app.store_ids', true), ',')::uuid[])
              );
            """
        )

    # ai_reader reads the new tables like any other (plan section 8.8)
    tables_csv = ", ".join(BUSINESS_TABLES)
    op.execute(f"GRANT SELECT ON {tables_csv}, daily_reconciliation TO ai_reader;")

    # --- app_user privileges (plan section 8.8) -----------------------------
    # No earlier migration ever granted app_user anything on any table, so
    # 0005's "REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM app_user" has
    # been revoking a privilege it never had — a silent no-op. This is the last
    # migration, so every table now exists: grant broad read/write here, then
    # re-apply the audit_logs restriction so it actually takes effect.
    op.execute("GRANT USAGE ON SCHEMA public TO app_user;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;")
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM app_user;")


def downgrade() -> None:
    # Mirror the upgrade grants before anything is dropped, so a later DROP
    # ROLE app_user (in 0001's downgrade) has no remaining ACL entries to
    # block it — REVOKE ON ALL TABLES/SEQUENCES only reaches what still exists
    # at the point it runs.
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM app_user;")
    op.execute("REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM app_user;")
    op.execute("REVOKE USAGE ON SCHEMA public FROM app_user;")

    tables_csv = ", ".join(BUSINESS_TABLES)
    # noqa justification: BUSINESS_TABLES is a module-level list of literal
    # table names, not input, and DDL cannot take bind parameters.
    op.execute(
        f"REVOKE SELECT ON {tables_csv}, daily_reconciliation FROM ai_reader;"  # noqa: S608
    )
    op.execute("DROP VIEW IF EXISTS daily_reconciliation;")
    for table in reversed(BUSINESS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS store_scope ON {table};")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        op.execute(f"DROP TABLE IF EXISTS {table};")
    op.execute("DROP TYPE IF EXISTS cheque_status;")
    op.execute("ALTER TABLE pages DROP COLUMN IF EXISTS storage_table;")
    op.execute("ALTER TABLE pages DROP COLUMN IF EXISTS is_system;")
